version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./app:/var/www/app/
      - ./logs/nginx:/var/log/nginx/
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    volumes:
      - ./app/:/var/www/app/
      - ./logs/php.log:/var/log/fpm-php.www.log
    environment:
      PHP_IDE_CONFIG: "serverName=${PHPSTORM_SERVER_NAME}"
    env_file: .env
#    extra_hosts:
#      - "host.docker.internal:host-gateway" # for Linux
networks:
  internal:
    driver: bridge