version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/prod.Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
  php:
    container_name: relokia-php-fpm-app
    build:
      context: .
      dockerfile: php/prod.Dockerfile
    networks:
      - internal
    env_file: .env

networks:
  internal:
    driver: bridge